export const Questions = [
    {
        prompt: "How do you say 'Good Morning'?",
        optionA: "E ka bo",
        optionB: "E ka san",
        optionC: "E ka ro",
        optionD: "e ka leh",
        answer: "C",
    },

    {
        prompt: "What does Kele n Sele'? mean",
        optionA: "What is happening",
        optionB: "How old are you?",
        optionC: "How are things?",
        optionD: "What poppin?",
        answer: "A",
    },

    {
        prompt: "How do you say 'Good Evening'?",
        optionA: "E ka bo",
        optionB: "E ka san",
        optionC: "E ka ro",
        optionD: "e ka leh",
        answer: "D",
    },
]