export const Questions = [
    {prompt: "How would you say 'Welcome' when you visit somebodies house",
     optionA: "E ka bo", 
     optionB: "E ka san", 
     optionC: "E Kule", 
     optionD: "e ka leh", 
     answer: "C",},

     {prompt: "How do you say 'Welcome' (Somebody visits you)",
     optionA: "E ka ro", 
     optionB: "E ka bo", 
     optionC: "o da ro", 
     optionD: "So wa dada", 
     answer: "B",},

     {prompt: "Translate 'goodbye'",
     optionA: "Kilo ruko e", 
     optionB: "O da san", 
     optionC: "O da bo", 
     optionD: "Odola", 
     answer: "C",},

     {prompt: "Translate 'till tommorrow'",
     optionA: "mi ni", 
     optionB: "O da ro", 
     optionC: "E ka san", 
     optionD: "Odola", 
     answer: "D",},

     {prompt: "Translate 'O tojo meta'",
     optionA: "It has been three days", 
     optionB: "All day Everyday", 
     optionC: "How have you been", 
     optionD: "Everything Good", 
     answer: "A",},
]